on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
          key: ffsimulator-${{ hashFiles('DESCRIPTION') }}-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: |
            ffsimulator-${{ hashFiles('DESCRIPTION') }}
            ffsimulator-

      - name: Install system dependencies
        run: |
          pak::local_system_requirements(execute = TRUE)
          pak::local_install_dev_deps()
          pak::pak("nflverse/nflreadr")
          pak::pak("ffverse/ffscrapr@dev")
          pak::pak("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}
